<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{57de771e-4346-4079-9379-3645d39749ca}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	fbHikrobotScannerCtrl		: FB_SCANNER_HikrobotEXT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//fbSiemensCameraMV5xCtrl();

//PRG_Test();
PRG_ButtonsHandler();

//IO_logic();

fbHikrobotScannerCtrl();

//Outer_IN_Case_Duplicat();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>