<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{57de771e-4346-4079-9379-3645d39749ca}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbSiemensCameraMV5xCtrl		: FB_SiemensCameraMV5xCtrl;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbSiemensCameraMV5xCtrl();

PRG_Test();
//PRG_ButtonsHandler();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>