<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_TEST" Id="{57de771e-4346-4079-9379-3645d39749ca}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	fbCaseDuplicatCheck_Test		: FB_CASE_DuplicatCheckTests;
	//fbCaseDuplicateUpdateToDB		: FB_CASE_DuplicateUpdateToDBTests;
	//fbCaseFinaliseData				: FB_CASE_FinaliseDataTests;
	//fbCaseInitialiseData_Test 		: FB_CASE_InitialiseDataTests;
	//fbCaseValidateContent			: FB_CASE_ValidateContentTests;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//===================================================
//UNIT TEST EXECUTION

TcUnit.RUN();

//===================================================
//MANUAL TEST EXECUTION

PRG_CASE_DuplicatCheckManual();
PRG_CASE_DuplicateUpdateToDBManual();
PRG_CASE_FinaliseDataManual();
PRG_CASE_InitialiseDataManual();
PRG_CASE_ValidateContentManual();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>